name: .NET Core Desktop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: USALauncher.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore and Build the solution
    - name: Restore and Build
      run: dotnet build $env:Solution_Name --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Publish the application with specified settings
    - name: Publish the application
      shell: pwsh  # Specify PowerShell as the shell
      run: |
        dotnet publish $env:Solution_Name --configuration $env:Configuration --output ./publish `
        --self-contained true `
        --runtime win-x64 `
        --publish-single-file true
      env:
        Configuration: ${{ matrix.configuration }}

    # Upload the build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: USALauncher
        path: ./publish
