name: "Deploy USALauncher"

on:
  push:
    tags:
      - "USALauncher/v*"  # Trigger on tags like "USALauncher/v1.0"

env:
  PROJECT_PATH: USALauncher/USALauncher.csproj  # Adjust this if your project file path is different

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Using the latest version

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Adjust the .NET version as necessarys

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build Project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1  # Use the create-release action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token
        with:
          tag_name: ${{ github.ref }}  # Use the tag that triggered the workflow
          release_name: ${{ github.ref }}  # Use the tag as the release name

      - name: Upload Release Assets
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: USALauncher/bin/Release/net8.0/win-x64/publish/*  # Adjust the path if necessary
          release-url: ${{ steps.create_release.outputs.upload_url }}
