name: .NET Core Desktop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: USALauncher.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore and Build the solution
    - name: Restore and Build
      run: dotnet build $env:Solution_Name --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Publish the application with specified settings
    - name: Publish the application
      shell: pwsh  # Specify PowerShell as the shell
      run: |
        dotnet publish $env:Solution_Name --configuration $env:Configuration --output ./publish `
        /p:SelfContained=true `
        /p:RuntimeIdentifier=win-x64 `
        /p:PublishSingleFile=true
      env:
        Configuration: ${{ matrix.configuration }}

    # Compress the output directory before uploading
    - name: Compress Publish Folder
      run: Compress-Archive -Path ./publish -DestinationPath USALauncher.zip

    # Split the ZIP file into smaller chunks (45MB each)
    - name: Split the ZIP file
      shell: pwsh
      run: |
        $chunkSize = 45MB  # Lowered chunk size to prevent issues
        $fileIndex = 0
        $filePath = "USALauncher.zip"
        $fileStream = [System.IO.File]::OpenRead($filePath)
        $buffer = New-Object byte[] $chunkSize

        while (($bytesRead = $fileStream.Read($buffer, 0, $chunkSize)) -gt 0) {
            $chunkFileName = "USALauncher.part$($fileIndex).zip"
            $fileIndex++
            $chunkStream = [System.IO.File]::Create($chunkFileName)
            $chunkStream.Write($buffer, 0, $bytesRead)
            $chunkStream.Close()
        }

        $fileStream.Close()

    # Upload each split part as an individual artifact
    - name: Upload split artifacts
      uses: actions/upload-artifact@v3
      with:
        name: USALauncher
        path: "*.part*.zip"
